# torch.Tensor

- torch.Tensor는 Tensor객체의 메소드
- 메소드 말고 속성도 있음(dtype, device, layout, memory_format)
- torch와 거의 유사
- torch와 비교해 In-place연산자(_)가 많음

In [ ]:
import numpy as np
import torch

## Tensor class reference

### Tensor.T (attribute)
- transpose
- memory 공유

In [ ]:
x = torch.rand(1, 2, 3, 4)

y = x.T # (4, 3, 2, 1)

y[2][1][0][0] = 100
print(y[2][1][0][0] == x[0][0][1][2])

print(y.shape)

tensor(True)
torch.Size([4, 3, 2, 1])


### Tensor.t()
- Tensor.t()
- 2차원 이하의 텐서만 지원
- 0차원과 1차원을 바꾼다
- memory 공유

In [ ]:
x = torch.rand(2, 5)

y = x.t()
y[0][1] = 100
print(y[0][1] == x[1][0])
print(y.shape)

y.t_() # in-place version

print(y.shape)

tensor(True)
torch.Size([5, 2])
torch.Size([2, 5])


### Tensor.new_tensor(), new_full(), new_empty(), new_ones() new_zeros()
- 새로운 텐서 반환
- 이해가 안가는 점은 Tensor.new_tensor(data) 이런 식이라는 점이다
- Tensor가 어떤 값인지 전혀 중요하지 않다, data를 갖는 텐서를 만든다
    - 그러면 torch.new_tensor(data) 이런 식이 더 낫지 않나? 어떤 목적으로 이렇게 만들어진걸까?

In [ ]:
x = torch.rand(5, 2)

x_new = x.new_tensor(torch.rand(4, 4))

x_new

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([[0.8645, 0.7358, 0.7237, 0.1308],
        [0.4840, 0.1035, 0.9089, 0.3443],
        [0.1960, 0.5444, 0.7848, 0.1441],
        [0.3978, 0.4933, 0.5694, 0.4149]])

### Tensor.is_cuda
- Is True if the Tensor is stored on the GPU, False otherwise.

In [17]:
x = torch.randint(10, (2, 3))
x.is_cuda

False

### Tensor.device
- Is the torch.device where this Tensor is.

In [15]:
x = torch.randint(10, (2, 2))
x.device

device(type='cpu')

### Tensor.cpu()
- Returns a copy of this object in CPU memory.
- If this object is already in CPU memory and on the correct device, then no copy is performed and the original object is returned

### Tensor.cuda()
- Returns a copy of this object in CUDA memory
- If this object is already in CUDA memory and on the correct device, then no copy is performed and the original object is returned.
- parameter: device (torch.device) – The destination GPU device. Defaults to the current CUDA device.

### Tensor.get_device()
- For CUDA tensors, this function returns the device ordinal of the GPU on which the tensor resides. 
- For CPU tensors, an error is thrown

### Tensor.backward()
- Computes the gradient of current tensor w.r.t.(with respect to) graph leaves.
- This function accumulates gradients in the leaves - you might need to zero .grad attributes or set them to None before calling it. 
- If you run any forward ops, create gradient, and/or call backward in a user-specified CUDA stream context, see [Stream semantics of backward passes](https://pytorch.org/docs/stable/notes/cuda.html#bwd-cuda-stream-semantics).

### Tensor.grad()
- This attribute is None by default and becomes a Tensor the first time a call to backward() computes gradients for self. 
- The attribute will then contain the gradients computed and future calls to backward() will accumulate (add) gradients into it.
_  loss.backward()를 호출하면 autograd는 gradient를 계산하고 이를 텐서의 .grad 속성(attribute)에 저장합니다

### Tensor.detach()
- Returns a new Tensor, detached from the current graph
- The result will never require gradient
- Returned Tensor shares the same storage with the original one.

### Tensor.numpy()
- Returns self tensor as a NumPy ndarray. This tensor and the returned ndarray share the same underlying storage.
- Changes to self tensor will be reflected in the ndarray and vice versa.

### Tensor.to()
- Performs Tensor dtype and/or device conversion
- Returns a Tensor with the specified device and (optional) dtype. If dtype is None it is inferred to be self.dtype. 
- dtype이나 device를 바꾸게 되면 memory는 share될 수 없을 것으로 예상

In [6]:
# >>> tensor = torch.randn(2, 2)  # Initially dtype=float32, device=cpu
# >>> tensor.to(torch.float64)
# tensor([[-0.5044,  0.0005],
#         [ 0.3310, -0.0584]], dtype=torch.float64)

# >>> cuda0 = torch.device('cuda:0')
# >>> tensor.to(cuda0)
# tensor([[-0.5044,  0.0005],
#         [ 0.3310, -0.0584]], device='cuda:0')

# >>> tensor.to(cuda0, dtype=torch.float64)
# tensor([[-0.5044,  0.0005],
#         [ 0.3310, -0.0584]], dtype=torch.float64, device='cuda:0')

# >>> other = torch.randn((), dtype=torch.float64, device=cuda0)
# >>> tensor.to(other, non_blocking=True)
# tensor([[-0.5044,  0.0005],
#         [ 0.3310, -0.0584]], dtype=torch.float64, device='cuda:0')

### Tensor.tolist()
- Returns the tensor as a (nested) list. For scalars, a standard Python number is returned, just like with item(). 
- Tensors are automatically moved to the CPU first if necessary.

In [11]:
x1 = torch.rand(2, 2)
x2 = torch.rand(1, 1)

y1 = x1.tolist()
y2 = x2.tolist()
y3 = x2.item()

print(y1, y2, y3)

[[0.7422759532928467, 0.22756850719451904], [0.4219493865966797, 0.029946625232696533]] [[0.2920449376106262]] 0.2920449376106262


### Tensor.item()
- Returns the value of this tensor as a standard Python number. This only works for tensors with one element. For other cases, see tolist().

### Tensor.abs(), abs_(), real(), imag()

### Tensor.apply_()

### Tensor.expand()
- Tensor.expand(*sizes)
- Returns a new view of the self tensor with singleton dimensions expanded to a larger size.

- Passing -1 as the size for a dimension means not changing the size of that dimension.
- More than one element of an expanded tensor may refer to a single memory location. As a result, in-place operations may result in incorrect behavior. If you need to write to the tensors, please clone them first.

### Tensor.repeat()
- Tensor.repeat(*sizes)
- Repeats this tensor along the specified dimensions.
- Unlike expand(), this function copies the tensor’s data.

### Tensor.argmax(), argmin(), argsort()

### Tensor.ceil(), floor()

### Tensor.clone()

### Tensor.copy_()

### Tensor.view()

### Tensor.contiguous()
- Returns a contiguous in memory tensor containing the same data as self tensor.
- If self tensor is already in the specified memory format, this function returns the self tensor.

### Tensor.is_contiguous()
- Returns True if self tensor is contiguous in memory in the order specified by memory format.

### Tensor.is_leaf()
- All Tensors that have requires_grad which is False will be leaf Tensors by convention.

- For Tensors that have requires_grad which is True, they will be leaf Tensors if they were created by the user. This means that they are not the result of an operation and so grad_fn is None.

- Only leaf Tensors will have their grad populated during a call to backward(). To get grad populated for non-leaf Tensors, you can use retain_grad().



In [7]:
# >>> a = torch.rand(10, requires_grad=True)
# >>> a.is_leaf
# True

# >>> b = torch.rand(10, requires_grad=True).cuda()
# >>> b.is_leaf
# False
# # b was created by the operation that cast a cpu Tensor into a cuda Tensor

# >>> c = torch.rand(10, requires_grad=True) + 2
# >>> c.is_leaf
# False
# # c was created by the addition operation

# >>> d = torch.rand(10).cuda()
# >>> d.is_leaf
# True
# # d does not require gradients and so has no operation creating it (that is tracked by the autograd engine)

# >>> e = torch.rand(10).cuda().requires_grad_()
# >>> e.is_leaf
# True
# # e requires gradients and has no operations creating it

# >>> f = torch.rand(10, requires_grad=True, device="cuda")
# >>> f.is_leaf
# True
# # f requires grad, has no operation creating it

### Tensor.is_shared()
- checks if tensor is in shared memory.
- This is always True for CUDA tensors.

### Tensor.flatten()
- torch.flatten(input, start_dim=0, end_dim=-1)
- Flattens input by reshaping it into a one-dimensional tensor.
- Numpy의 flatten은 항상 copy, tensor는 view될 수도, copy될 수도 -> tensor.reshape과 유사

In [4]:
x = torch.rand(2, 3, 4)

y1 = x.flatten()

y2 = x.flatten(start_dim=1)

y3 = x.flatten(start_dim=2)

y4 = x.flatten(end_dim=1)

print(y1.shape, y2.shape, y3.shape, y4.shape)

torch.Size([24]) torch.Size([2, 12]) torch.Size([2, 3, 4]) torch.Size([6, 4])


### Tensor.float(), bool(), char()

### Tensor.register_hook()

### Tensor.requires_grad(), requires_grad_()
- Is True if gradients need to be computed for this Tensor, False otherwise.
- The fact that gradients need to be computed for a Tensor do not mean that the grad attribute will be populated, see is_leaf for more details.

### Tensor.size()

### Tensor.to_sparse()

### Tensor.type(), type_as()

In [3]:
import torch
x = torch.rand(1, 2)
print(x.type())
print(type(x))

torch.FloatTensor
<class 'torch.Tensor'>


### Tensor.unfold()

### Tensor.unique()